CREATE TABLE variants (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    item_id        BIGINT                   NOT NULL,
    sku            VARCHAR(64)              NOT NULL,
    name           VARCHAR(150)             NOT NULL,
    price          NUMERIC(12, 2)           NOT NULL,
    stock_quantity INTEGER                  NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_variants PRIMARY KEY (id),
    -- RESTRICT: an item that still has variants (and therefore stock records) cannot be deleted.
    CONSTRAINT fk_variants_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT,
    CONSTRAINT uk_variants_sku UNIQUE (sku),
    CONSTRAINT ck_variants_price_non_negative CHECK (price >= 0),
    -- Last line of defence against overselling, independent of application code.
    CONSTRAINT ck_variants_stock_non_negative CHECK (stock_quantity >= 0)
);

CREATE INDEX idx_variants_item_id ON variants (item_id);
